name: 🐞 [Business Approvals Kit] Bug report
description: File a bug report for the Business Approvals Kit
title: "[Business Approvals Kit - BUG] ISSUE TITLE"
labels: ["bug"]
assignees: []
body:
- type: textarea
  attributes:
    label: Describe the issue
    description: A concise description of what you're experiencing. Please provide as much related information as possible including screenshots, documents, links etc.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen. Please provide as much related information as possible including screenshots, documents, links etc.
  validations:
    required: false
- type: input
  id: version
  attributes:
    label: What solution version are you using?
    placeholder: "1.70"
  validations:
    required: true
- type: input
  id: app
  attributes:
    label: What app or flow are you having the issue with?
    placeholder: "BACore | Approval Time-out"
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
