Settings:
  IgnoreColors: True
  IgnoreTextIfNotVisible: True

IgnoreVariableSetup:
  - Constants

IgnoreProperties:
  - ItemKey
  - ItemIconName
  - IconName
  - Image
  - FieldName
  - FieldType
  - Column

IgnoreValues:
  - SuggestionKey
  - SuggestionName
  - SuggestionRole

IgnoreFunctions:
  - SortByColumns
  - ShowColumns
  - Trace
  - LookUp