Settings:
  IgnoreColors: True
  IgnoreTextIfNotVisible: True

IgnoreVariableSetup:
  - Constants

IgnoreProperties:
  - ItemKey
  - ItemIconName
  - IconName
  - Image
  - FieldName
  - FieldType
  - Column
  - FieldVariantName
  - OnSearch

IgnoreValues:
  - SuggestionKey
  - SuggestionName
  - SuggestionRole
  - SuggestionImgUrl
  

IgnoreFunctions:
  - SortByColumns
  - ShowColumns
  - Trace
  - LookUp