Settings:
  IgnoreColors: True

IgnoreVariableSetup:
  - Constants

IgnoreProperties:
  - ItemKey
  - ItemIconName
  - IconName
  - Image
  - FieldName
  - FieldType

IgnoreFunctions:
  - SortByColumns