# Pipeline to create a Github release for the CoE Starter Kit solution
parameters:
- name: ReleaseMonthNumber
  type: number
- name: ReleaseYearNumber
  type: number
- name: CloseMilestoneIssues
  type: boolean
  default: false
- name: DraftRelease
  type: boolean
  default: true
- name: HotfixReleaseNumber
  type: number
  default: 0
- name: PrepareAppSourcePackage
  type: boolean
  default: false
- name: PreparePackageDeployerPackage
  type: boolean
  default: false
  
trigger: none
pr: none
resources:
  repositories:
  - repository: PipelineRepo  # repository name (DO NOT CHANGE THIS VALUE) 
    type: github
    ref: Rajeev-ts-release #main # If your pipeline templates are in a branch other than the default branch specify the branch here. Otherwise the default branch will be used by default.
    endpoint: powercat-alm # Specifies the GitHub service connection for this setup.
    name: Microsoft/coe-alm-accelerator-templates  #This is the name of the repo in the current project in Azure Devops that has the pipeline templates. If the repo is in a different project you can specify the project and repo using the format ProjectContainingTheBuildTemplates/RepositoryContainingTheBuildTemplates (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#type)
pool:
  vmImage: 'windows-2019'

variables:
- group: alm-accelerator-variable-group

steps:
# Checkout our GitHub Branch
- checkout: self
  displayName: 'Checkout Source Branch'

# Download the artifacts from the latest deployment of BusinessApprovalKitConnector to production.
- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    project: 'powercat-business-approvals-kit'
    pipeline: '2027' #Production buildId
    runVersion: 'latest'
    patterns: '**/BusinessApprovalKit*.zip'
  displayName: 'Download Business Approval Kit solution'

- powershell: |
    New-Item -Path $(Pipeline.Workspace)\releaseassets -ItemType Directory
    New-Item -Path $(Pipeline.Workspace)\assetstaging -ItemType Directory
    Copy-Item '$(Pipeline.Workspace)\drop\*managed.zip' -Destination '$(Pipeline.Workspace)\assetstaging'
    Copy-Item '$(Build.SourcesDirectory)\powercat-business-approvals-kit\ApprovalsKitResources\Release\Collateral\ApprovalsKit\*.*' -Destination '$(Pipeline.Workspace)\assetstaging'

    $compress = @{
      Path = '$(Pipeline.Workspace)\assetstaging\*.*'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)\releaseassets\BusinessApprovalsKit.zip'
    }
    Compress-Archive @compress

    Copy-Item '$(Pipeline.Workspace)\drop\*managed.zip' -Destination '$(Pipeline.Workspace)\releaseassets'
    Remove-Item $(Pipeline.Workspace)\drop\*managed.zip -Recurse -Force -Confirm:$false
    Remove-Item $(Pipeline.Workspace)\assetstaging -Recurse -Force -Confirm:$false
    New-Item -Path $(Pipeline.Workspace)\assetstaging -ItemType Directory

    Copy-Item '$(Pipeline.Workspace)/drop/BusinessApprovalKit*.zip' -Destination '$(Pipeline.Workspace)\assetstaging'    
    
    $compress = @{
      Path = '$(Pipeline.Workspace)\assetstaging\*.*'
      CompressionLevel = 'Fastest'
      DestinationPath = '$(Pipeline.Workspace)/releaseassets/BusinessApprovalKit-Unmanaged.zip'
    }
    Compress-Archive @compress

    $templateTag = 'BusinessApprovalsKit-$(ReleaseMonthName)${{parameters.ReleaseYearNumber}}'
    $templateTitle = 'Business Approvals Kit $(ReleaseMonthName) ${{parameters.ReleaseYearNumber}}'
    if(${{parameters.HotfixReleaseNumber}} -ne 0) {
        $templateTag = 'BusinessApprovalsKit-$(ReleaseMonthName)${{parameters.ReleaseYearNumber}}-HF${{parameters.HotfixReleaseNumber}}'
        $templateTitle = 'Business Approvals Kit $(ReleaseMonthName) ${{parameters.ReleaseYearNumber}} - Hotfix ${{parameters.HotfixReleaseNumber}}'
    }
    Write-Host "##vso[task.setvariable variable=TemplateTag]$templateTag"
    Write-Host "##vso[task.setvariable variable=TemplateTitle]$templateTitle"    
  displayName: 'Prepare release assets'

- template: Pipelines\Templates\create-release-github.yml@PipelineRepo
  parameters:
    gitHubApiUrl: 'microsoft/powercat-business-approvals-kit'
    solutionName: 'BusinessApprovalKit'
    solutionDisplayName: 'Business Approval Kit'
    releaseMonth: ${{parameters.ReleaseMonthNumber}}
    releaseYear: ${{parameters.ReleaseYearNumber}}
    connectionName: 'powercat-alm'
    releaseNotesPath: 'powercat-business-approvals-kit/ApprovalsKitResources/Release/Notes/'
    issueClosingComment: 'This has been fixed in the latest release.'
    closeIssues: ${{parameters.CloseMilestoneIssues}}
    isDraft: ${{parameters.DraftRelease}}
    isPreRelease: false
    hotfixReleaseNumber: ${{parameters.HotfixReleaseNumber}}
    queryHeadingDelimited: ""
    prepareAppSourcePackage: ${{parameters.PrepareAppSourcePackage}}
    preparePackageDeployerPackage: ${{parameters.PreparePackageDeployerPackage}}
    projectName: "powercat-business-approvals-kit"
