name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false    

jobs:
  print-issue-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue Milestone
        run: echo "The milestone of your issue is ${{ github.event.issue.milestone.title }}"

  alertEnhancementAK:
    if: |
      contains(github.event.issue.labels.*.name, 'enhancement')
    runs-on: ubuntu-latest    
    steps:
      - name: Get Milestone Name
        id: milestone
        run: echo "::set-output name=name::${{ github.event.issue.milestone.title }}"

      - name: Extract Month
        id: extract-month
        run: echo "::set-output name=month::$(echo ${{ steps.milestone.outputs.name }} | rev | cut -d' ' -f1 | rev)"

      - name: Set Iteration Path
        id: set-iteration
        run: echo "::set-output name=iteration::OneCatTools\\FY24\\Q2\\${{ steps.extract-month.outputs.month }}"
