name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned, milestoned]
  issue_comment:
    types: [created, edited, deleted]
concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false    

jobs:
  mainjob1:
    runs-on: ubuntu-latest
    outputs:
      var1: ${{ steps.set_var.outputs.var1 }}
    steps:
      - name: Set Variable
        id: set_var
        run: |
          echo "var1=good" >> $GITHUB_OUTPUT

  mainjob2:
    needs: mainjob1
    runs-on: ubuntu-latest
    steps:
      - name: Access Variable
        run: |
          echo "var1=${{ needs.mainjob1.outputs.var1 }}"  
