name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false    

jobs:
  alertEnhancementAK:
    if: |
      contains(github.event.issue.labels.*.name, 'enhancement')
    runs-on: ubuntu-latest    
    steps:
      - name: Set Milestone
        id: set-milestone
        run: echo "MILESTONE=${{ github.event.issue.milestone.title }}" >> $GITHUB_ENV

      - name: Print Milestone
        run: echo "Milestone is ${{ env.MILESTONE }}"        
        
      - name: Extract Month
        id: extract-month
        run: echo "MONTH=$(echo $MILESTONE | rev | cut -d' ' -f2 | rev)" >> $GITHUB_ENV
        
      - name: Print Extracted Month
        run: echo "Extracted Month ${{ env.MONTH }}"

      - name: Extract Year
        id: extract-year
        run: echo "YEAR=$(echo $MILESTONE | cut -d' ' -f3)" >> $GITHUB_ENV
  
      - name: Replace first two characters with 'FY'
        id: replace-fy
        run: echo "YEAR=$(echo $YEAR | sed 's/^../FY/')" >> $GITHUB_ENV
        
      - name: Print FY Year
        run: echo "Formatted year - ${{ env.YEAR }}"        
        
      - name: Set Iteration Path
        id: set-iteration
        run: echo "ITERATION=OneCatTools\\FY${{ env.FY }}\\Q2\\$MONTH" >> $GITHUB_ENV

      - name: Print the Iteration Path
        run: echo "Iteration Path ${{ env.ITERATION }}"        

      - name: Sync to Azure DevOps
        uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "cattools"
          ado_project: "OneCatTools"
          ado_area_path: "OneCatTools\\ApprovalsKit\\Develop"
          ado_iteration_path: "${{ env.ITERATION }}"
          ado_wit: "User Story"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Resolved"
          ado_bypassrules: true
          log_level: 100
